language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install requests
  - pip install PrettyTable
# command to run tests
script:
  - pytest --cov prettytable
  - python -m unittest project_03.py
